name: Build FongMi Source
on:
  schedule:
    # 每日自动更新，可自行修改cron
    - cron: '0 4 * * *'
  workflow_dispatch: # 支持手动触发
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install jq python3-pip -y
          pip install base58

      - name: Download config.js
        run: |
          wget -O raw_config.js https://pz.v88.qzz.io?format=2&source=full

      - name: Base58 decode & export source.json
        run: |
          python3 << 'EOF'
          import base58
          with open("raw_config.js", "r", encoding="utf-8") as f:
              b58_str = f.read().strip()
          raw_json_bytes = base58.b58decode(b58_str)
          raw_json = raw_json_bytes.decode("utf-8")
          with open("source.json", "w", encoding="utf-8") as out:
              out.write(raw_json)
          print("Decode success, saved to source.json")
EOF

      - name: Convert CMS source.json to FongMi json
        run: |
          jq '
          {
            sites: [
              .api_site | to_entries[] | {
                key: (.key | split(".")[0] | gsub("www";"") | gsub("[.]";"")),
                name: .value.name,
                type: 3,
                api: .value.api,
                searchable: 1,
                changeable: 1,
                recordable: 1
              }
            ]
          }
          ' source.json > fongmi_vod.json

      - name: Commit & push generated file
        run: |
          git config user.name "Auto Bot"
          git config user.email "bot@github.com"
          git add fongmi_vod.json
          if git diff --staged --quiet; then
            echo "No changes, skip commit"
          else
            git commit -m "Auto update fongmi_vod.json from remote cdn config"
            git push
          fi
